Repository snowball-lang/snowball, pull requests merged in 2023-12, with the labels that each got.

#152 Make repo a flake and make ld-linux be dynamically located
  .envrc
  .gitignore
  CMakeLists.txt
  flake.lock
  flake.nix
  src/builder/linker/linux/ld.cc
Labels: enhancement, good first issue

#156 fix: have crt* located by dlopen and make repo a flake
  .envrc
  .gitignore
  CMakeLists.txt
  flake.lock
  flake.nix
  src/builder/linker/linux/ld.cc
Labels: enhancement, good first issue, help wanted

#158 New macros as well as new macro syntax! `env`, `include_str`, `alignof`, `sizeof`, and many more!
  .github/workflows/test.yml
  src/constants.h
  src/parser/parseExpr.cc
  src/visitors/TransformContext.h
  src/visitors/transform/utils/initializePerModuleMacros.cc
  src/visitors/transform/utils/transformMacro.cc
  src/visitors/transform/visits/Expression/PseudoVariable.cc
  stdlib/Assert.sn
  stdlib/Core.sn
  stdlib/Optional.sn
  stdlib/Panic.sn
  stdlib/Ptr.sn
  stdlib/SourceLocation.sn
  tests/algorithms.sn
  tests/assets/macros_test.txt
  tests/chars.sn
  tests/macros.sn
  tests/numbers.sn
  tests/source_location.sn
  tests/syntax.sn
  tests/vector.sn
Labels: enhancement, good first issue, help wanted

#161 Added and tested `Map`
  src/builder/llvm/buildLLVMFunction.cc
  src/visitors/transform/utils/bodyReturns.cc
  stdlib/map.sn
  stdlib/tuples.sn
  tests/main.sn
  tests/map.sn
Labels: enhancement

#163 Added iter modules
  src/visitors/transform/utils/transformTypeExtension.cc
  stdlib/iter.sn
  stdlib/std.sn
  tests/iters.sn
  tests/main.sn
  tests/vector.sn
Labels: enhancement

#164 Fix releases for macos builds and unix like release builds
  .github/workflows/test.yml
  CMakeLists.txt
  README.md
  app/commands/init.h
  build_scripts/release_build.sh
  runtime/libs/backtrace.cc
  runtime/libs/backtracing.h
  runtime/libs/exceptions.cc
  runtime/libs/exceptions.h
  runtime/libs/segfault.cc
  scripts/install.sh
  snowball.version.id
  snowball.version.str
  src/ast/cache/FunctionCache.cc
  src/ast/types/DefinedType.cc
  src/builder/linker/macos/ld.cc
  src/builder/llvm/initializeVariable.cc
  stdlib/map.sn
  tests/lambdas.sn
  tests/main.sn
  tests/map.sn
  tests/string.sn
Labels: bug, good first issue, help wanted

#165 Fixed that you can't check if reference's base type implements an interface
  build_scripts/install_deps.sh
  src/visitors/transform/utils/executeGenericTests.cc
Labels: bug

#166 Automatically casted arguments sometimes don't work
  .vscode/launch.json
  src/ast/syntax/common.h
  src/builder/llvm/buildConstant.cc
  src/parser/parseClass.cc
  src/visitors/transform/utils/transformClass.cc
  src/visitors/transform/visits/Expression/ConstantValue.cc
  stdlib/std.sn
  tests/main.sn
Labels: bug

#168 Added modules for doc generator
  .vscode/launch.json
  app/commands/docgen.h
  sn.toml
  src/ast/syntax/nodes.h
  src/compiler.cc
  src/compiler.h
  src/parser/parseComment.cc
  src/parser/parseGlobal.cc
  src/parser/parseMacro.cc
  src/parser/parseNamespace.cc
  src/visitors/Transformer.cc
  src/visitors/analyzers/DAV/Block.cc
  src/visitors/analyzers/DAV/Expression/BinaryOperator.cc
  src/visitors/analyzers/DAV/Expression/Identifier.cc
  src/visitors/analyzers/DAV/Expression/Index.cc
  src/visitors/analyzers/DAV/Expression/LambdaFunction.cc
  src/visitors/analyzers/DAV/Macro.cc
  src/visitors/analyzers/DAV/MiddlePlace.cc
  src/visitors/analyzers/DAV/Statements/Conditional.cc
  src/visitors/analyzers/DAV/Statements/ForLoop.cc
  src/visitors/analyzers/DAV/Statements/FunctionDef.cc
  src/visitors/analyzers/DAV/Statements/TryCatch.cc
  src/visitors/analyzers/DAV/Statements/VariableDecl.cc
  src/visitors/analyzers/DAV/Statements/WhileLoop.cc
  src/visitors/analyzers/DAV/Statements/visitConstructor.cc
  src/visitors/analyzers/DAV/defaults.cc
  src/visitors/analyzers/DAVUtils.cc
  src/visitors/documentation/DocGen.cc
  src/visitors/documentation/DocGen.h
  src/visitors/documentation/DocTemplates.cc
  src/visitors/documentation/DocTemplates.h
  stdlib/__winter_wonderland__.sn
  stdlib/c_bindings.sn
  stdlib/std.sn
  tests/syntax.sn
Labels: documentation

#169 Added macros support for documentation generator
  .vscode/launch.json
  src/ast/syntax/exprs.cc
  src/ast/syntax/nodes.h
  src/visitors/documentation/DocGen.cc
  src/visitors/documentation/DocTemplates.cc
  src/visitors/documentation/DocTemplates.h
Labels: documentation

#171 Added support for namespaces in documentation generator
  src/visitors/documentation/DocGen.cc
  src/visitors/documentation/DocGen.h
  src/visitors/documentation/DocTemplates.cc
  src/visitors/documentation/DocTemplates.h
  stdlib/fs/path.sn
  stdlib/std.sn
Labels: documentation

#174 Fix paths and files for function overloads in doc generator
  src/visitors/documentation/DocGen.h
  src/visitors/documentation/DocTemplates.cc
Labels: documentation

#175 Added support for variables in documentation generator
  app/commands/docgen.h
  src/compiler.cc
  src/compiler.h
  src/parser/parseClass.cc
  src/parser/parseConstant.cc
  src/visitors/documentation/DocGen.cc
  src/visitors/documentation/DocGen.h
  src/visitors/documentation/DocTemplates.cc
  src/visitors/documentation/DocTemplates.h
  tests/cls.sn
Labels: documentation

#185 Added the `std::strings` module and the `\xXX` scape character support
  src/lexer/lexer.cc
  stdlib/chars.sn
  stdlib/strings.sn
  tests/main.sn
  tests/strings.sn
Labels: enhancement
